# Generated by Django 6.1 on 2026-09-02 01:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tail_number", models.CharField(max_length=20)),
                ("manufacturer_serial_number", models.CharField(max_length=20)),
                ("aircraft_type", models.CharField(max_length=50)),
                ("seat_map", models.JSONField(blank=True, default=dict)),
                ("operational_state", models.CharField(max_length=20)),
                (
                    "fuel_on_board_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "flight_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("flight_cycles", models.PositiveIntegerField()),
            ],
        ),
    ]
