# Generated by Django 6.1 on 2026-09-02 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraft",
            name="operational_state",
        ),
        migrations.AddField(
            model_name="aircraft",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aircraft",
            name="last_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="next_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_GROUND", "On Ground (Available)"),
                    ("IN_FLIGHT", "In Flight"),
                    ("MAINTENANCE", "Maintenance"),
                    ("GROUNDED", "Grounded"),
                    ("RETIRED", "Retired / Decommissioned"),
                ],
                default="ON_GROUND",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="tail_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
