# Generated by Django 6.1 on 2026-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_remove_aircraft_operational_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
