# Generated by Django 6.1 on 2026-09-02 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="technician",
            name="technician_availability",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("BUSY", "Busy"),
                    ("LEAVE", "On Leave"),
                    ("INACTIVE", "Inactive"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="technician_name",
            field=models.CharField(default="Unknown Technician", max_length=100),
        ),
        migrations.AddField(
            model_name="technician",
            name="technician_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="technician",
            name="technician_specialization",
            field=models.CharField(
                choices=[
                    ("AIRFRAME", "Airframe & Structural Mechanics"),
                    ("AVIONICS", "Avionics & Electrical Systems"),
                    ("POWERPLANT", "Powerplant & Propulsion"),
                    ("HYDRAULICS", "Hydraulics & Mechanical Systems"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
