# Generated by Django 6.1 on 2026-09-03 00:31

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_workorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=20, unique=True)),
                ("part_description", models.TextField()),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                ("minimum_stock_level", models.PositiveIntegerField(default=0)),
                ("manufacturer", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="technician",
            name="technician_number",
            field=models.CharField(default="TECH-000", max_length=20, unique=True),
        ),
    ]
