# Generated by Django 6.1 on 2026-09-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0007_inventorytransaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorytransaction",
            old_name="created_at",
            new_name="transaction_date",
        ),
    ]
