# Generated by Django 6.1 on 2026-09-03 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0008_rename_created_at_inventorytransaction_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transactions",
                to="fleet.technician",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.PositiveIntegerField(default=1)),
                ("quantity_used", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_requirements",
                        to="fleet.part",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="required_parts",
                        to="fleet.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workorder",
            name="parts",
            field=models.ManyToManyField(
                blank=True,
                related_name="work_orders",
                through="fleet.WorkOrderPart",
                to="fleet.part",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderpart",
            constraint=models.UniqueConstraint(
                fields=("work_order", "part"), name="unique_work_order_part"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderpart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_used__lte", models.F("quantity_required"))
                ),
                name="quantity_used_not_greater_than_required",
            ),
        ),
    ]
