# Generated by Django 6.1 on 2026-09-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_alter_inventorytransaction_technician_workorderpart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transactions",
                to="fleet.workorder",
            ),
        ),
    ]
